
const prefix = "DMS_ENROLLER/"

export const GET_ALL_DMS_ENROLLER = prefix + 'GET_ALL_DMS_ENROLLER';
export const GET_ALL_DMS_ENROLLER_SUCCESS = prefix + 'GET_ALL_DMS_ENROLLER_SUCCESS';
export const GET_ALL_DMS_ENROLLER_ERROR = prefix + 'GET_ALL_DMS_ENROLLER_ERROR';

export const GET_DMS_ENROLLER_CERT = prefix + 'GET_DMS_ENROLLER_CERT';
export const GET_DMS_ENROLLER_CERT_SUCCESS = prefix + 'GET_DMS_ENROLLER_CERT_SUCCESS';
export const GET_DMS_ENROLLER_CERT_ERROR = prefix + 'GET_DMS_ENROLLER_CERT_ERROR';

export const CREATE_DMS_ENROLLER_REQUEST_VIA_CSR_REQUEST = prefix + 'CREATE_DMS_ENROLLER_REQUEST_VIA_CSR_REQUEST';
export const CREATE_DMS_ENROLLER_REQUEST_VIA_CSR_REQUEST_SUCCESS = prefix + 'CREATE_DMS_ENROLLER_REQUEST_VIA_CSR_REQUEST_SUCCESS';
export const CREATE_DMS_ENROLLER_REQUEST_VIA_CSR_REQUEST_ERROR = prefix + 'CREATE_DMS_ENROLLER_REQUEST_VIA_CSR_REQUEST_ERROR';

export const CREATE_DMS_ENROLLER_REQUEST_VIA_FORM_REQUEST = prefix + 'CREATE_DMS_ENROLLER_REQUEST_VIA_FORM_REQUEST';
export const CREATE_DMS_ENROLLER_REQUEST_VIA_FORM_REQUEST_SUCCESS = prefix + 'CREATE_DMS_ENROLLER_REQUEST_VIA_FORM_REQUEST_SUCCESS';
export const CREATE_DMS_ENROLLER_REQUEST_VIA_FORM_REQUEST_ERROR = prefix + 'CREATE_DMS_ENROLLER_REQUEST_VIA_FORM_REQUEST_ERROR';

export const UPDATE_DMS_ENROLLER_STATUS = prefix + 'UPDATE_DMS_ENROLLER_STATUS';
export const UPDATE_DMS_ENROLLER_STATUS_SUCCESS = prefix + 'UPDATE_DMS_ENROLLER_STATUS_SUCCESS';
export const UPDATE_DMS_ENROLLER_STATUS_ERROR = prefix + 'UPDATE_DMS_ENROLLER_STATUS_ERROR';

export const DELETE_LAST_PRIV_KEY = prefix + 'DELETE_LAST_PRIV_KEY';
