
const prefix = "devices/"

export const GET_ALL_DEVICES = prefix + 'GET_ALL_DEVICES';
export const GET_ALL_DEVICES_SUCCESS = prefix + 'GET_ALL_DEVICES_SUCCESS';
export const GET_ALL_DEVICES_ERROR = prefix + 'GET_ALL_DEVICES_ERROR';

export const GET_DEVICE = prefix + 'GET_DEVICE';
export const GET_DEVICE_SUCCESS = prefix + 'GET_DEVICE_SUCCESS';
export const GET_DEVICE_ERROR = prefix + 'GET_DEVICE_ERROR';

export const GET_DEVICE_LOGS = prefix + 'GET_DEVICE_LOGS';
export const GET_DEVICE_LOGS_SUCCESS = prefix + 'GET_DEVICE_LOGS_SUCCESS';
export const GET_DEVICE_LOGS_ERROR = prefix + 'GET_DEVICE_LOGS_ERROR';

export const GET_DEVICE_LAST_ISSUED_CERT = prefix + 'GET_DEVICE_LAST_ISSUED_CERT';
export const GET_DEVICE_LAST_ISSUED_CERT_SUCCESS = prefix + 'GET_DEVICE_LAST_ISSUED_CERT_SUCCESS';
export const GET_DEVICE_LAST_ISSUED_CERT_ERROR = prefix + 'GET_DEVICE_LAST_ISSUED_CERT_ERROR';

export const GET_DEVICE_CERT_HISTORY= prefix + 'GET_DEVICE_CERT_HISTORY';
export const GET_DEVICE_CERT_HISTORY_SUCCESS = prefix + 'GET_DEVICE_CERT_HISTORY_SUCCESS';
export const GET_DEVICE_CERT_HISTORY_ERROR = prefix + 'GET_DEVICE_CERT_HISTORY_ERROR';

export const GET_DEVICE_DMSs = prefix + 'GET_DEVICE_DMSs';
export const GET_DEVICE_DMSs_SUCCESS = prefix + 'GET_DEVICE_DMSs_SUCCESS';
export const GET_DEVICE_DMSs_ERROR = prefix + 'GET_DEVICE_DMSs_ERROR';

export const CREATE_DEVICE = prefix + 'CREATE_DEVICE';
export const CREATE_DEVICE_SUCCESS = prefix + 'CREATE_DEVICE_SUCCESS';
export const CREATE_DEVICE_ERROR = prefix + 'CREATE_DEVICE_ERROR';

export const DELETE_DEVICE = prefix + 'DELETE_DEVICE';
export const DELETE_DEVICE_SUCCESS = prefix + 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_ERROR = prefix + 'DELETE_DEVICE_ERROR';

export const PROVISION_DEVICE = prefix + 'PROVISION_DEVICE';
export const PROVISION_DEVICE_SUCCESS = prefix + 'PROVISION_DEVICE_SUCCESS';
export const PROVISION_DEVICE_ERROR = prefix + 'PROVISION_DEVICE_ERROR';

export const PROVISION_DEVICE_CSR = prefix + 'PROVISION_DEVICE_CSR';
export const PROVISION_DEVICE_CSR_SUCCESS = prefix + 'PROVISION_DEVICE_CSR_SUCCESS';
export const PROVISION_DEVICE_CSR_ERROR = prefix + 'PROVISION_DEVICE_CSR_ERROR';

export const RENEW_DEVICE = prefix + 'RENEW_DEVICE';
export const RENEW_DEVICE_SUCCESS = prefix + 'RENEW_DEVICE_SUCCESS';
export const RENEW_DEVICE_ERROR = prefix + 'RENEW_DEVICE_ERROR';

export const REVOKE_DEVICE_CERT = prefix + 'REVOKE_DEVICE_CERT';
export const REVOKE_DEVICE_CERT_SUCCESS = prefix + 'REVOKE_DEVICE_CERT_SUCCESS';
export const REVOKE_DEVICE_CERT_ERROR = prefix + 'REVOKE_DEVICE_CERT_ERROR';

export const GET_DMS_CERT_HISTORY_LAST_30_DAYS = prefix + 'GET_DMS_CERT_HISTORY_LAST_30_DAYS';
export const GET_DMS_CERT_HISTORY_LAST_30_DAYS_SUCCESS = prefix + 'GET_DMS_CERT_HISTORY_LAST_30_DAYS_SUCCESS';
export const GET_DMS_CERT_HISTORY_LAST_30_DAYS_ERROR = prefix + 'GET_DMS_CERT_HISTORY_LAST_30_DAYS_ERROR';
