
const prefix = "dms/"

export const GET_ALL_DMS = prefix + 'GET_ALL_DMS';
export const GET_ALL_DMS_SUCCESS = prefix + 'GET_ALL_DMS_SUCCESS';
export const GET_ALL_DMS_ERROR = prefix + 'GET_ALL_DMS_ERROR';

export const GET_DMS_CERT = prefix + 'GET_DMS_CERT';
export const GET_DMS_CERT_SUCCESS = prefix + 'GET_DMS_CERT_SUCCESS';
export const GET_DMS_CERT_ERROR = prefix + 'GET_DMS_CERT_ERROR';

export const CREATE_DMS_VIA_CSR_REQUEST = prefix + 'CREATE_DMS_VIA_CSR_REQUEST';
export const CREATE_DMS_VIA_CSR_REQUEST_SUCCESS = prefix + 'CREATE_DMS_VIA_CSR_REQUEST_SUCCESS';
export const CREATE_DMS_VIA_CSR_REQUEST_ERROR = prefix + 'CREATE_DMS_VIA_CSR_REQUEST_ERROR';

export const CREATE_DMS_VIA_FORM_REQUEST = prefix + 'CREATE_DMS_VIA_FORM_REQUEST';
export const CREATE_DMS_VIA_FORM_REQUEST_SUCCESS = prefix + 'CREATE_DMS_VIA_FORM_REQUEST_SUCCESS';
export const CREATE_DMS_VIA_FORM_REQUEST_ERROR = prefix + 'CREATE_DMS_VIA_FORM_REQUEST_ERROR';

export const UPDATE_DMS_STATUS = prefix + 'UPDATE_DMS_STATUS';
export const UPDATE_DMS_STATUS_SUCCESS = prefix + 'UPDATE_DMS_STATUS_SUCCESS';
export const UPDATE_DMS_STATUS_ERROR = prefix + 'UPDATE_DMS_STATUS_ERROR';

export const DELETE_LAST_PRIV_KEY = prefix + 'DELETE_LAST_PRIV_KEY';
